server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_user
    username: root
    password: santosh@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: HikariCP
      connection-timeout: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: UserService
